Return DateTime multiplier (by 1000)
TeskaLabs/asab-webui pull request #109
Opened 2021-05-17 12:51 UTC by titkov49

Because of misunderstood I deleted multiplier by 1000 in DateTime component. On SCRUM meeting we decided that it should stay.

<img width="1440" alt="Screenshot 2021-05-17 at 14 49 52" src="https://user-images.githubusercontent.com/37152497/118491392-3ec68980-b71f-11eb-89b5-9613ed01eca6.png">
<img width="1440" alt="Screenshot 2021-05-17 at 14 50 05" src="https://user-images.githubusercontent.com/37152497/118491396-4128e380-b71f-11eb-9df6-521a4de984a4.png">

2021-05-17 13:52 UTC, ateska commented
We discussed the "smart" detection of the unit based on the range of the value provided.

2021-05-18 10:55 UTC, titkov49 commented
@ateska @Pe5h4 @wuujcik 
Now DateTime component define which type of timestamp (in seconds or in milliseconds) was passed base on length of this number. It of course has own limits. For timestamp in seconds it is max value which is **9999999999** (Nov 20, 2286 6:46 PM). For timestamp in milliseconds it is min value which is ** 10000000000** (Apr 26, 1970 6:46 PM).

2021-05-18 10:55 UTC, titkov49 commented
<img width="1440" alt="Screenshot 2021-05-18 at 12 39 33" src="https://user-images.githubusercontent.com/37152497/118639588-5e6db880-b7d8-11eb-9bff-8d81b6c8d1f4.png">

2021-05-18 11:29 UTC, ateska commented on src/containers/DateTime.js
> +* Number with timestamp in milliseconds (min value is 10000000000)
Add the example with `Date.now()` please - it is quite relevant here.

2021-05-18 11:30 UTC, ateska requested changes

2021-05-18 11:30 UTC, ateska commented on src/containers/DateTime.js
> +		value.toString().length > 10 ? moment(value) : moment(value * 1000);
`value >= 9999999999` ??

2021-05-18 11:33 UTC, ateska requested changes
One remark, then mergeable.

2021-05-18 16:40 UTC, ateska approved these changes

2021-05-19 07:16 UTC, Pe5h4 approved these changes

2021-05-19 08:08 UTC, merged