Feature/wizard
TeskaLabs/asab-webui pull request #127
Opened 2021-06-22 12:27 UTC by titkov49

Continuing to work on asab-webui wizard. Created new module for Wizard

2021-06-23 08:24 UTC, ateska approved these changes

2021-06-23 14:22 UTC, Pe5h4 requested changes

2021-06-23 14:22 UTC, Pe5h4 commented on src/abc/Module.js
> +        this.Config = app?.config;
@titkov49 Why do you need to define Config, Navigation and Router in here? Also, I think it should be without `?`. Also, be patient with the indentation on line 6 and 7

2021-06-23 14:22 UTC, Pe5h4 commented on src/modules/wizard/WizardContainer.js
> +    console.log(json)
@titkov49 Here is some forgotten console.log

2021-06-23 14:22 UTC, Pe5h4 commented on src/modules/wizard/index.js
> +        console.log("WizardModule: ", this);
@titkov49 Here is some forgotten console.log

2021-06-23 14:22 UTC, Pe5h4 commented on src/modules/wizard/mock-data.json
> +{
@titkov49 Do we need mocked data in the `modules/wizard`? It might be better, if it would be a part of documentation or `public` folder

2025-01-08 11:30 UTC, Pe5h4 commented
Closing for obsolescence

2025-01-08 11:30 UTC, closed without merging