Move about page to sidebar
TeskaLabs/asab-webui pull request #138
Opened 2021-07-14 12:29 UTC by t-pyrope

2021-07-14 12:58 UTC, t-pyrope commented
![screencapture-localhost-3000-2021-07-14-11_03_25](https://user-images.githubusercontent.com/57274895/125625836-16d43c3b-3d1a-415c-bad8-c121e3a8881c.png)

![screencapture-localhost-3000-2021-07-14-11_04_05](https://user-images.githubusercontent.com/57274895/125625857-cdcc80ab-caed-4de9-af64-541039b9e0fb.png)

2021-07-14 16:19 UTC, Pe5h4 requested changes
Also, I miss the update in `CHANGELOG` file

2021-07-14 16:19 UTC, Pe5h4 commented on src/modules/about/index.js
> +		// app.Navigation.addItem({
@t-pyrope Why is the navigation commented?

2021-07-14 16:19 UTC, Pe5h4 commented on src/modules/about/index.js
> +		// app.Navigation.addItem({
Here is the proper place to add a navigation, not in `asab-config` module

2021-07-14 16:19 UTC, Pe5h4 commented on src/modules/asab-config/index.js
> +import AboutScreen from '../about/AboutScreen';
@t-pyrope This is wrong, you dont want to import `About` screen to the `asab-config` module, please remove your implemented code from this `src/modules/asab-config/index.js` file

2021-07-15 07:09 UTC, t-pyrope commented
![screencapture-chrome-extension-fdpohaocaechififmbbbbbknoalclacl-capture-html-2021-07-15-08_34_35](https://user-images.githubusercontent.com/57274895/125744794-4db669fe-b072-4556-bff8-c89976775f4b.png)

2021-07-15 07:25 UTC, Pe5h4 approved these changes

2021-07-15 07:25 UTC, Pe5h4 commented on src/modules/asab-config/index.js
> +				},
@t-pyrope It is not neccessary to have a comma separator here

2021-07-15 09:01 UTC, ateska approved these changes

2021-07-16 13:51 UTC, merged