Refactor/about page
TeskaLabs/asab-webui pull request #142
Opened 2021-07-27 14:02 UTC by t-pyrope

From Aleš:

> re: About screen and versioning.
> I revisited this topic and I came to following conclusion:
> - product name, web site link and email are generic and they should be read from configuration (as is implemented today)
>- version and build date (not release date!) is specific for a component

> This means that they cannot be part of the config.
> A version and a build date need to be wrapped into a dedicated container (eg. card) with title “User interface” (there will be more containers for other components in the future).
> The card is optional to display, the information to be read from the file that is produced by Dima build script - the build date needs to be added there, on the second line.

![screencapture-localhost-3000-2021-07-27-15_51_11](https://user-images.githubusercontent.com/57274895/127167497-df4482dd-9d8d-40b4-b9d3-ca42660af111.png)

![screencapture-localhost-3000-2021-07-27-15_51_22](https://user-images.githubusercontent.com/57274895/127167530-907cdd1c-0d7e-4f36-9539-7016178260b7.png)

![screencapture-localhost-3000-2021-07-27-15_51_36](https://user-images.githubusercontent.com/57274895/127167550-80f4e076-0270-43fa-b580-f538e222cab4.png)

![screencapture-localhost-3000-2021-07-27-15_51_47](https://user-images.githubusercontent.com/57274895/127167567-b75f59e7-17ea-41bc-9ceb-9e584d6fc636.png)

2021-07-28 08:06 UTC, ateska requested changes
The translation:
"Datum sestaveni"

... and this should be below a version

2021-07-28 08:06 UTC, ateska commented on doc/user-interface.md
> +	path: '/auth/interface',
The "User interface" card should be part of the About screen: a card below the existing card.
Not the dedicated router entry.

2021-07-28 08:21 UTC, ateska commented
![about](https://user-images.githubusercontent.com/2236975/127289281-8e6135ba-183e-4f4b-99a3-36ff2bc23d35.png)

... the idea is that various components can add their cards on the about page.

2021-07-28 10:20 UTC, titkov49 commented
@t-pyrope Code looks good to me. It can be merged once all change requests above is solved. 
And can you also provide screenshots please?

2021-07-28 10:21 UTC, titkov49 reviewed
@t-pyrope Code looks good to me. It can be merged once all change requests above is solved.
And can you also provide screenshots please?

2021-07-28 10:40 UTC, t-pyrope commented
![screencapture-localhost-3000-2021-07-28-12_34_37](https://user-images.githubusercontent.com/57274895/127309170-9dcc689f-223e-41e4-8457-d2251c9c55ed.png)

![screencapture-localhost-3000-2021-07-28-12_33_51](https://user-images.githubusercontent.com/57274895/127309174-b6cc0260-a113-4a2d-a1c9-19f202c13fef.png)

![yarn build](https://user-images.githubusercontent.com/57274895/127309175-d2d350f9-d515-4520-a8fb-d0a5c2ae049a.png)

2021-07-28 10:45 UTC, t-pyrope commented
![screencapture-localhost-3000-2021-07-28-12_43_12](https://user-images.githubusercontent.com/57274895/127309716-5a14b814-2ba4-450d-994d-d81f15069e6d.png)

![screencapture-localhost-3000-2021-07-28-12_42_17](https://user-images.githubusercontent.com/57274895/127309735-13dc0aa1-3970-41a4-b523-3e044b671804.png)

2021-07-28 11:42 UTC, t-pyrope commented
![screencapture-localhost-3000-2021-07-28-13_39_09](https://user-images.githubusercontent.com/57274895/127316624-b3c6cf65-f9da-45cb-aa26-775df00fd355.png)

2021-07-28 13:04 UTC, Pe5h4 requested changes
@t-pyrope Also, the translation of `User interface` is `Uživatelské rozhraní` and I want to know, why there is the grayish gap in the sidebar? Also dont implement `CardFooter`.

![127309716-5a14b814-2ba4-450d-994d-d81f15069e6d](https://user-images.githubusercontent.com/45622755/127326674-7f2a1686-520e-4040-ab40-500e6540dc36.png)

2021-07-28 13:26 UTC, ateska requested changes
I see on screenshot that there is a "card footer" - we don't need that.

2021-07-28 13:26 UTC, ateska commented on src/modules/about/UserInterfaceCard.js
> +						<h5>{t('UserInterfaceCard|Last build')}</h5>
It is not a last build but "Build date"

2021-07-29 04:25 UTC, t-pyrope commented on src/modules/about/AboutCard.js
> +						<Link to={webSiteLink}>{webSiteName}</Link>
Sorry, it's my Chrome extension for screenshots. It's not a grayish gap in original

![Animation5](https://user-images.githubusercontent.com/57274895/127431336-abfbb843-8b96-4c54-b8d7-8b8a233681f5.gif)

2021-07-29 04:35 UTC, t-pyrope commented
![logman](https://user-images.githubusercontent.com/57274895/127432227-019f92e5-49fa-4456-8736-a203e2621c7f.png)

![logman2](https://user-images.githubusercontent.com/57274895/127432243-ac156ebe-51de-45d3-b008-715a7fabe1b5.png)

![Animation5](https://user-images.githubusercontent.com/57274895/127432252-f7c40c95-6f56-4214-8e41-2468d8412c85.gif)

2021-07-29 07:53 UTC, titkov49 approved these changes
Good job.  It can be merged.

2021-07-29 10:17 UTC, Pe5h4 requested changes

2021-07-29 10:17 UTC, Pe5h4 commented on src/modules/about/AboutCard.js
> +						<a href="https://teskalabs.com" target="_blank" rel="noopener noreferrer">
@t-pyrope I dont think the link nor the text should be `hardcoded` here. It should go to the config as well.

2021-07-29 11:31 UTC, ateska requested changes
Last remark, then mergeable from my perspective.

2021-07-29 11:31 UTC, ateska commented on src/modules/about/AboutCard.js
> +						<h5>{t('AboutCard|Vendor')}</h5>
Vendor should go first, then the website and then email.

2021-07-29 12:09 UTC, t-pyrope commented
![logman](https://user-images.githubusercontent.com/57274895/127489213-92bffbeb-843d-4752-a250-429c39947864.png)

![logman-cz](https://user-images.githubusercontent.com/57274895/127489225-80295245-b613-4d47-ba74-174b3ce2defe.png)

2021-07-29 13:08 UTC, ateska approved these changes

2021-07-29 15:52 UTC, Pe5h4 approved these changes

2021-07-30 05:11 UTC, merged