Draft: Hide row with empty version
TeskaLabs/asab-webui pull request #171
Opened 2021-09-14 10:23 UTC by t-pyrope

2021-09-14 13:03 UTC, titkov49 approved these changes

2021-09-14 15:24 UTC, Pe5h4 commented
@t-pyrope Can you also hide website, when it will not be set?
https://github.com/TeskaLabs/asab-webui/blob/master/src/modules/about/AboutCard.js#L50

2021-09-14 15:25 UTC, Pe5h4 requested changes
@t-pyrope Can you also hide website please, when it is not set?

https://github.com/TeskaLabs/asab-webui/blob/master/src/modules/about/AboutCard.js#L50

2021-09-16 10:40 UTC, t-pyrope commented
![about](https://user-images.githubusercontent.com/57274895/133598090-380fdbbc-acfe-4bf9-8dd1-843705ced08c.png)

2021-09-16 16:14 UTC, Pe5h4 approved these changes

2021-09-17 05:43 UTC, merged