Filter those breadcrumbs items which doesn't have names
TeskaLabs/asab-webui pull request #196
Opened 2021-11-04 22:29 UTC by titkov49

Now items which doesn't have names won't be rendered in breadcrumbs (e.g. library container).
Also breadcrumbs with only one item will be rendered. (e.g. export container)
<img width="1430" alt="Screenshot 2021-11-04 at 23 16 55" src="https://user-images.githubusercontent.com/37152497/140429174-68adacbf-6c17-44dc-8ec2-872ee2d19fac.png">
<img width="1430" alt="Screenshot 2021-11-04 at 23 18 58" src="https://user-images.githubusercontent.com/37152497/140429181-c4216195-bca0-4f27-a0cb-6be50cefd93d.png">
<img width="1430" alt="Screenshot 2021-11-04 at 23 20 37" src="https://user-images.githubusercontent.com/37152497/140429183-c7d3ea39-10b2-4bd6-9358-1f57521f53c5.png">

2021-11-05 11:09 UTC, ateska approved these changes

2021-11-05 15:13 UTC, Pe5h4 requested changes

2021-11-05 15:13 UTC, Pe5h4 commented on src/containers/Breadcrumbs.js
> +								: <span>{crumb.name}</span>
@titkov49 I think we should also add translations for breadcrumbs

2021-11-09 11:24 UTC, Pe5h4 approved these changes

2021-11-09 12:00 UTC, merged