collapsable header
TeskaLabs/asab-webui pull request #214
Opened 2021-12-02 13:32 UTC by petrKavulok

2021-12-06 14:36 UTC, petrKavulok commented
https://user-images.githubusercontent.com/79644454/144863929-a9fbbef6-d3d5-4758-8d05-266f34cc4a0c.mov

2021-12-07 08:46 UTC, Pe5h4 requested changes
Anyway, it looks good! I would use better naming of variables and I am not sure about that `caret` toggler for displaying the header properties. Can you add some images how it would look like e.g. with some other icons like 
https://icons.coreui.io/icons/linear/chevron-circle-left-alt/
https://icons.coreui.io/icons/linear/chevron-circle-down-alt/

https://icons.coreui.io/icons/linear/chevron-left/
https://icons.coreui.io/icons/linear/chevron-bottom/

2021-12-07 08:46 UTC, Pe5h4 commented on src/containers/Header/index.js
> +		<header className={userbarOpen ? 'op' : ''}>
@petrKavulok I think here you can simplify the condition this way

```
userBarOpen && "op"
```
Also, I would use better naming - 

`userbarOpen` >>> `headerProperties`
`op` >>> `open`

or something with similar meaning

2021-12-07 08:46 UTC, Pe5h4 commented on src/containers/Header/index.js
> +					<Nav className="ml-auto user-bar" navbar>
@petrKavulok Also request for renaming

`user-bar` >>> `header-props`

2021-12-07 09:18 UTC, petrKavulok commented
I like the first one the most, the ones pointing to the side don't make much sense to me
https://user-images.githubusercontent.com/79644454/144999881-de261b8c-996c-4bd6-a346-07e51bb88245.mov


https://user-images.githubusercontent.com/79644454/144999889-c3f276bd-a75a-404d-81c8-df39e688025a.mov


https://user-images.githubusercontent.com/79644454/144999890-af6a0d1e-a409-497f-9f11-fc5bac6ea65a.mov


https://user-images.githubusercontent.com/79644454/145000845-91646c9e-5bed-4da4-b9f1-6d0bac45a597.mov

2021-12-07 13:04 UTC, ateska commented
Number 1 looks cool to me.

2021-12-07 13:04 UTC, ateska approved these changes

2021-12-07 14:56 UTC, Pe5h4 approved these changes
Ok, looks fine. From what I have seen the first toggler was the best

2021-12-07 18:20 UTC, merged