Update Config module with displaying dynamic values in with patternProperties in schema
TeskaLabs/asab-webui pull request #219
Opened 2021-12-08 14:56 UTC by Pe5h4

2021-12-14 16:26 UTC, Pe5h4 commented
@ateska This is the first iteration of refactorization of ASAB-Config module based on friday's discussion and outputs

If there will be anything broader to add/refactor from you or something unclear, we can have a short call about it.

Values to render and section (pattern)properties are stored in formStruct in following flow described in points:

After data from endpoints are obtained:
 1] add sections and section keys from properties to formStruct with appropriate data (if properties present in the schema)
https://github.com/TeskaLabs/asab-webui/blob/a8d7e819d99300392a405b53ad36528bb3634841/src/modules/asab-config/ConfigContainers/ConfigEditor.js#L109
 https://github.com/TeskaLabs/asab-webui/blob/a8d7e819d99300392a405b53ad36528bb3634841/src/modules/asab-config/ConfigContainers/ConfigEditor.js#L115
 2] add sections and section keys from patternProperties to formStruct with appropriate data (if patternProperties sections are present in the schema)
https://github.com/TeskaLabs/asab-webui/blob/a8d7e819d99300392a405b53ad36528bb3634841/src/modules/asab-config/ConfigContainers/ConfigEditor.js#L144
https://github.com/TeskaLabs/asab-webui/blob/a8d7e819d99300392a405b53ad36528bb3634841/src/modules/asab-config/ConfigContainers/ConfigEditor.js#L148

https://github.com/TeskaLabs/asab-webui/blob/a8d7e819d99300392a405b53ad36528bb3634841/src/modules/asab-config/ConfigContainers/ConfigEditor.js#L176-L181

 3] add rest of the values to adHoc
https://github.com/TeskaLabs/asab-webui/blob/a8d7e819d99300392a405b53ad36528bb3634841/src/modules/asab-config/ConfigContainers/ConfigEditor.js#L171-L174
 4] set values from formStruct and from adHoc for register (with the usage of `setValue` comonent of react-hook-form)
https://github.com/TeskaLabs/asab-webui/blob/a8d7e819d99300392a405b53ad36528bb3634841/src/modules/asab-config/ConfigContainers/ConfigEditor.js#L186-L201
 5] render input forms and data according to formStruct properties
https://github.com/TeskaLabs/asab-webui/blob/a8d7e819d99300392a405b53ad36528bb3634841/src/modules/asab-config/ConfigContainers/ConfigEditor.js#L307-L328

Sections with adHoc cannot be saved now (it does not fit the schema, service is throwing errors) and support for patternProperties will be added as well (now we cannot save values to configs with patternProperties) - I discussed this with Mithun and he is going to work on that next sprint.

Here is the flow with examples of configuration with adHoc sections or/and adHoc keys (values). On gif image there is also an example of schemas with patternProperties (and as well with adHocs):

![config-refactorisation](https://user-images.githubusercontent.com/45622755/146033490-5d39d43f-ea4b-4145-b113-828be764df43.gif)

I have also question - should we support nested patternProperties (meant for keys)? I suppose for our `section-key-value` configs this wont be necessary. Here is the example:

```
...
 "patternProperties": {
        "^section:source:(?<varname>.*)$": {
            "type": "object",
            "title": "Section configuration",
            "description": "Secition source",
            "default": {},
            "examples": [
                {
                    "^section:source:name:(?<keyname>.*)$": "My Key"
                }
            ],
            "required": [
                "^section:source:name:(?<keyname>.*)$"
            ],
            "patternProperties": {
                "^section:source:name:(?<keyname>.*)$": {
                    "type": "string",
                    "title": "Name",
                    "description": "Fill the name of the Key",
                    "default": "",
                    "examples": [
                        "MyOwnKey"
                    ]
                }
            },
            "additionalProperties": false
        },
...
```

2021-12-15 09:11 UTC, ateska commented
Support for the `pattern on key` will be added eventually (if ever).

2021-12-15 09:17 UTC, ateska requested changes
Few remarks but this is a brilliant direction.

2021-12-15 09:17 UTC, ateska commented on src/modules/asab-config/ConfigContainers/ConfigEditor.js
> +		let fs = {};
Here we need more descriptive variable name.

2021-12-15 09:17 UTC, ateska commented on src/modules/asab-config/ConfigContainers/ConfigEditor.js
> +		let data = {};
Here we need more descriptive variable name, `data` doesn't reveal too much.

2021-12-22 14:14 UTC, Pe5h4 commented
@ateska Updates:
- variable names for formStruct renamed https://github.com/TeskaLabs/asab-webui/blob/4ab015a9c5c620246a068dcb7ce2746f569c6b9d/src/modules/asab-config/ConfigContainers/ConfigEditor.js#L98-L100
- feature to handle cases, when key-value is not present in the configuration, but schema is present for this case (it can be the case of an empty config) https://github.com/TeskaLabs/asab-webui/blob/4ab015a9c5c620246a068dcb7ce2746f569c6b9d/src/modules/asab-config/ConfigContainers/ConfigEditor.js#L118-L122 - empty string is added to the section-key (we cannot use undefined value since it would not be rendered properly, but we can use empty string for every input type [number, boolean, etc.])
- implemented function to convert values based on value types on submit. onSubmit function converts all the updated values to string, so it has to be parsed back by the appropriate `type` before data are being processed to the service (as we discussed yesterday with you and Mithun) https://github.com/TeskaLabs/asab-webui/blob/4ab015a9c5c620246a068dcb7ce2746f569c6b9d/src/modules/asab-config/ConfigContainers/ConfigEditor.js#L313
- I commented editing values from JSON viewer (so now it is disabled), since you can specify the type of the value from JSON viewer and if you choose the wrong one, the configuration will not be saved. Anyway from what I remember, we were speaking of removing the JSON view completely in the future.
- other minor updates as seen from the commits

When Mithun will provide functional update on asab-config service, I will add a new gif image with the flow

2021-12-22 23:40 UTC, ateska commented
Looks good to me so far.

2022-01-06 11:41 UTC, Pe5h4 commented
@ateska In addition to above updates you have already aware of, I extended documentation for asab-config module (schema and config examples, supported input types) https://github.com/TeskaLabs/asab-webui/blob/da080a3fb044fdfe07dd33b922b36be40e305ad4/doc/asab-config.md

The creation of new (empty) configuration from asab-config module and sorting sections in the tree menu by name (as we spoke of) will be done in the next iteration

Here is the read/save flow for properties and pattern properties also with ad hoc values and ad hoc sections:
![pattern-props-asab-config](https://user-images.githubusercontent.com/45622755/148376518-87e93524-2fa9-4852-b9d5-4e077d544f27.gif)

2022-01-06 12:20 UTC, ateska commented
Why there is `config` in  `/config/Discover` path in the URL? ... that seems to be dangerous to me.

2022-01-06 12:22 UTC, ateska commented
Also word "key" in the config item is a bit redundant already.

2022-01-06 12:44 UTC, ateska commented
Tenant value in a config needs to be removed.

Let's have a review workshop for this, there are few additional remarks I have.

2022-01-06 15:14 UTC, ateska approved these changes

2022-01-06 16:44 UTC, Pe5h4 commented
> Why there is `config` in `/config/Discover` path in the URL? ... that seems to be dangerous to me.

@ateska This is a path to the config section. We decided to have path URL as `config/sectionName/configName`, (default is `config/$/$`) so the `config/Discover` just points to the section.

2022-01-06 16:49 UTC, Pe5h4 commented
> Also word "key" in the config item is a bit redundant already.

@ateska Yes, this is for the purpose of exercise. The name or the description is taken from the schema. Anyway, we should have a workshop about how to properly configure schemas (I suppose also together with Mithun)

Anyway, lets have a talk about it on the review, I will merge it only if there will be only after the review and only if there will be minors, which can be done in the next iteration.

2022-01-07 14:07 UTC, merged