Microservices - Add configurable items count limit
TeskaLabs/asab-webui pull request #223
Opened 2022-01-11 01:56 UTC by titkov49

2022-01-13 02:17 UTC, titkov49 commented
https://user-images.githubusercontent.com/37152497/149253989-81eabab2-e816-43c0-8ab2-7f608e7df2d3.mov

2022-01-17 17:33 UTC, Pe5h4 approved these changes

2022-01-17 22:04 UTC, ateska requested changes
Small remark, then mergeable.

2022-01-17 22:04 UTC, ateska commented on src/modules/asab-config/MicroservicesContainers/MicroservicesContainer.js
> +	const [limit, setLimit] = useState(10);
Default should be 20, other values 50 and 100.

2022-01-20 23:28 UTC, titkov49 commented
![Screenshot 2022-01-21 at 0 24 12](https://user-images.githubusercontent.com/37152497/150438304-336fe471-d3ce-4351-a2e9-406ead253923.png)
![Screenshot 2022-01-21 at 0 24 24](https://user-images.githubusercontent.com/37152497/150438306-61de3398-5e33-44be-a320-f47ca7c035f8.png)
![Screenshot 2022-01-21 at 0 27 53](https://user-images.githubusercontent.com/37152497/150438352-2ac9b542-e458-41b2-91fe-1d31c889982a.png)

2022-01-21 21:12 UTC, ateska approved these changes

2022-01-22 04:08 UTC, merged