Library module
TeskaLabs/asab-webui pull request #231
Opened 2022-02-07 12:34 UTC by titkov49

2022-02-07 12:37 UTC, titkov49 commented
https://user-images.githubusercontent.com/37152497/152789301-add6d0e3-ccb7-4b75-b9ca-df38ae7bf90f.mov

2022-02-07 13:32 UTC, ateska approved these changes
Yes, this is exactly what we need.

2022-02-07 17:07 UTC, Pe5h4 requested changes
@titkov49 Can you please write some small documentation on Library (how to use it) and add to the doc file also locales used in the Library container? Thanks! Otherwise looks great!

2022-02-11 10:53 UTC, petrKavulok approved these changes

2022-02-14 08:20 UTC, Pe5h4 approved these changes

2022-02-14 10:48 UTC, merged