Library upload
TeskaLabs/asab-webui pull request #250
Opened 2022-03-09 20:32 UTC by titkov49

2022-03-30 11:36 UTC, titkov49 commented
![Screenshot 2022-03-30 at 13 29 51](https://user-images.githubusercontent.com/37152497/160825843-03c9b802-86aa-48a3-a15e-672374cfdb2d.png)
![Screenshot 2022-03-30 at 13 29 56](https://user-images.githubusercontent.com/37152497/160825853-4636f7ef-34cd-47ac-822b-49be08765925.png)
![Screenshot 2022-03-30 at 13 30 03](https://user-images.githubusercontent.com/37152497/160825854-40e9ceba-d6b3-48a0-86a0-eea865330aee.png)
![Screenshot 2022-03-30 at 13 30 09](https://user-images.githubusercontent.com/37152497/160825856-856a804b-2181-4f5e-9041-3d89a6b1dfca.png)
![Screenshot 2022-03-30 at 13 30 16](https://user-images.githubusercontent.com/37152497/160825859-d9dc4786-3390-449f-8272-be89f1b10187.png)

2022-03-31 12:44 UTC, Pe5h4 requested changes
It looks nice, I dont see any issues right now, only minor updates. Also, can you please put translations of Library to `demo` app public folder?

2022-03-31 12:44 UTC, Pe5h4 commented on src/modules/library/containers/Import.js
> +			if (response.data.result !== "OK") throw new Error(`Response result is ${response.data.result}. Expected result is OK`);
@titkov49 Instead of `Expected result is OK` would be better to write that `File has not been uploaded`

2022-03-31 12:44 UTC, Pe5h4 commented on src/modules/library/containers/Import.js
> +							<p>{t("ASABLibraryModule|Choose library you want to import (only tar files are allowed) and type of importing")}</p>
Can it be as following?

```
<p>{t("ASABLibraryModule|Choose library and type for import")}</p>
<p style={{color: "#c8ced3", size: "8px"}}>{t("ASABLibraryModule|Only tar files are allowed")}</p>
```
That `Only tar files are allowed` looks like a hint (similar to FormText)

2022-04-01 11:18 UTC, ateska requested changes
Feedback provided during a review.

Library upload should be implemented as a Bootstrap form.

2022-04-07 14:10 UTC, titkov49 commented
https://user-images.githubusercontent.com/37152497/162219042-34a039cd-4ff5-4d6e-a06c-cf3f23275d38.mov

2022-04-07 14:12 UTC, titkov49 commented
@ateska @Pe5h4 re-review please

2022-04-07 19:00 UTC, ateska approved these changes

2022-04-08 08:20 UTC, Pe5h4 approved these changes
Dont forget to update locales in bs-ui and lmio-ui

2022-04-08 10:31 UTC, merged