DataTable Fix render TableCell for "parent"
TeskaLabs/asab-webui pull request #289
Opened 2022-06-17 10:15 UTC by Aringoaway

correct render data for row <td> for parent

2022-06-17 10:16 UTC, Aringoaway commented
![image](https://user-images.githubusercontent.com/65866093/174278933-7eb45a63-c661-4483-b98b-ce942e54b0ed.png)

2022-06-17 12:35 UTC, Pe5h4 requested changes
@Aringoaway Please add the change to changelog, otherwise cool!

2022-06-20 09:12 UTC, Pe5h4 approved these changes

2022-06-20 09:18 UTC, ateska approved these changes
Nice.
Let's test that on users ;-)

2022-06-20 11:04 UTC, merged