Dropdown hover style
TeskaLabs/asab-webui pull request #314
Opened 2022-07-07 12:17 UTC by Aringoaway

add hover style for dropdown

2022-07-07 12:27 UTC, Pe5h4 requested changes

2022-07-08 11:42 UTC, Aringoaway commented
@Pe5h4 can you review pls
![bg-dr](https://user-images.githubusercontent.com/65866093/177985646-dc43319b-7084-4761-9cf1-4a73b57af37b.gif)

2022-07-08 11:48 UTC, Pe5h4 approved these changes

2022-07-08 11:48 UTC, Pe5h4 commented on src/styles/components/dropdown.scss
> +	& .input-group-text, & .input-group-prepend {
@Aringoaway I think the same style should be implemented for `input-group-append`

2022-07-08 11:56 UTC, merged