Button issues removal
TeskaLabs/asab-webui pull request #357
Opened 2022-09-12 14:28 UTC by petrKavulok

outline moved within when active, btn link underline removed

2022-09-13 08:14 UTC, petrKavulok commented
### in this MR

- text color change when active
before

https://user-images.githubusercontent.com/79644454/189703614-e45f5244-44a0-401b-a442-d9f3dea96f11.mov


after

https://user-images.githubusercontent.com/79644454/189703638-e508021c-a497-4885-b131-c9c2c5f269df.mov

- active buttons drop shadow now appeares on the inside of the button

https://user-images.githubusercontent.com/79644454/189848194-df807b8a-56dd-4a32-9128-f875fb8c2f74.mov

- underline removed from link buttons

2022-09-13 08:18 UTC, Pe5h4 requested changes
Good! But please add this change to changelog

2022-09-14 07:36 UTC, Pe5h4 approved these changes

2022-09-14 07:38 UTC, Aringoaway approved these changes

2022-09-14 09:57 UTC, merged