add loaded class and style
TeskaLabs/asab-webui pull request #359
Opened 2022-09-15 11:13 UTC by Aringoaway

This MR goes with the other MR [Seacat-auth-webui](https://github.com/TeskaLabs/seacat-auth-webui/pull/4)

2022-09-19 14:52 UTC, Pe5h4 requested changes

2022-09-20 05:51 UTC, Aringoaway commented on src/styles/index.scss
> +		background-color: #f3f4fa;
@Pe5h4 Yes, you're right. It is better to use a variable $gray for this

2022-09-21 16:13 UTC, Pe5h4 approved these changes

2022-09-26 16:03 UTC, Pe5h4 requested changes

2022-09-26 16:03 UTC, Pe5h4 commented on demo/public/index.html
> +		<link rel="stylesheet" href="styles.css">
@Aringoaway Pls rename

2022-09-27 07:44 UTC, Pe5h4 approved these changes

2022-09-27 07:50 UTC, merged