Fix Card-Header styles
TeskaLabs/asab-webui pull request #377
Opened 2022-11-22 08:22 UTC by Aringoaway

2022-11-22 08:25 UTC, Aringoaway commented
This MR comes together with this [MR](http://gitlab.teskalabs.int/bitswan/bitswan-webui/-/merge_requests/183)

2022-11-25 15:49 UTC, Pe5h4 requested changes
@Aringoaway Please add changelog

2022-11-28 08:29 UTC, Pe5h4 approved these changes

2022-11-28 08:29 UTC, Pe5h4 commented
PLease resolve conflicts in changelog

2022-11-28 10:57 UTC, merged