Remove Helmet / Update addAlerts
TeskaLabs/asab-webui pull request #392
Opened 2023-02-20 08:53 UTC by Aringoaway

2023-02-21 16:52 UTC, Pe5h4 requested changes

2023-02-21 16:52 UTC, Pe5h4 commented on src/components/Credentials.js
> +			props.app.addAlert("warning", t("ASABCredentials|Something went wrong, failed to fetch assigned credentials", {error: e?.response?.data?.message}), 30);
@Aringoaway This and all other refactored alert updates are wrong here. It should be like that:

```
props.app.addAlert("warning", `${t("ASABCredentials|Something went wrong, failed to fetch assigned credentials")}. ${e?.response?.data?.message}`, 30);
```
```

2023-02-23 08:39 UTC, Pe5h4 commented
@Aringoaway How does the app look like without helmet? (the tab)

2023-02-23 13:46 UTC, Aringoaway commented
https://user-images.githubusercontent.com/65866093/220924700-e977ec9d-40f2-4fbf-af5f-60847cc3e494.mp4

2023-02-23 16:07 UTC, Pe5h4 approved these changes

2023-02-23 16:07 UTC, Pe5h4 commented
dont forget to update all apps with this change

2023-02-24 07:15 UTC, merged