Refactor/locales
TeskaLabs/asab-webui pull request #432
Opened 2023-06-30 10:56 UTC by queuing4oranges

- replacing dynamic values in locales - in asab-webui

-- when locales is loaded normally:

https://github.com/TeskaLabs/asab-webui/assets/31582696/7b0d5275-1eb5-4842-b4be-1a1bacbbb649

-- when the locales file is corrupted:

https://github.com/TeskaLabs/asab-webui/assets/31582696/a1aff49c-d8d9-4f37-995f-6a1628e97140

2023-06-30 14:37 UTC, Pe5h4 requested changes
@queuing4oranges Ok, this looks good - dont forget to update also locales in `demo` app and add the changelog. Btw. the videos can be displayed because of corrupted content :)

2023-07-03 15:10 UTC, queuing4oranges commented
replacing locales in asab-webui `demo` app

when locales load normally:

https://github.com/TeskaLabs/asab-webui/assets/31582696/94de72ef-ebaf-4cd8-93cb-6316948691f1

when locales file is corrupted:


https://github.com/TeskaLabs/asab-webui/assets/31582696/e2212610-80f5-4d85-aca9-da2f33693378


hope the video works!

2023-07-03 15:51 UTC, Pe5h4 requested changes
@queuing4oranges Small change request

2023-07-03 15:51 UTC, Pe5h4 commented on src/components/Pagination.js
> +				(`${t("of")} ${pages.length} ${t("Page")}`)}
@queuing4oranges Here I believe we want to have sometjing like:

```
{pages && (pages.length > 1) ? (`${t("of")} ${(lastPage == 0) ? 1 : lastPage} ${t("Pages")}`) : (`${t("of")} ${(lastPage == 0) ? 1 : lastPage} ${t("Page")}`)}
```

2023-07-06 09:16 UTC, merged