Fix sending props for TreeMenuItem
TeskaLabs/asab-webui pull request #446
Opened 2023-08-16 12:20 UTC by aringocode

TreeMenuItem needs to receive only resources and resource from `props`. Necessary parameters for library work come from `params`. Passing `props` completely causes errors in console, because these data are inserted as arguments to tags. 

If these changes pass inspection, I can contact Katya to have her update this on the microfrontend. And I can also update our applications to remove this bug in other applications.

2023-08-16 12:25 UTC, aringocode commented
@Pe5h4 can you review pls?

2023-08-16 15:53 UTC, Pe5h4 requested changes
@aringocode Ok, gut, Missing changelog. Can you please update that also in asab-webui-components?

2023-08-17 04:08 UTC, aringocode commented
> @aringocode Ok, gut, Missing changelog. Can you please update that also in asab-webui-components?

Yeah, sure. I'll update that. Can I make the changes right away in the maste in asab-webui-componentsr?

2023-08-18 13:49 UTC, Pe5h4 commented
> > @aringocode Ok, gut, Missing changelog. Can you please update that also in asab-webui-components?
> 
> @Pe5h4 Yeah, sure. I'll update that. Can I make the changes right away in the maste in asab-webui-componentsr?

Not the master, please create a branch, thanks :)

2023-08-18 13:50 UTC, Pe5h4 approved these changes

2023-08-21 11:46 UTC, merged