Add custom configurable Spinner component
TeskaLabs/asab-webui pull request #95
Opened 2021-04-21 13:39 UTC by wuujcik

Implementing the spinner as a component of ASAB-webUI so that we can reuse it easily in other projects

2021-04-21 15:29 UTC, ateska approved these changes

2021-04-21 16:40 UTC, Pe5h4 approved these changes

2021-04-22 07:24 UTC, Pe5h4 requested changes
Can you mention the spinner component it in the changelog file?

2021-04-22 08:33 UTC, Pe5h4 approved these changes

2021-04-22 08:34 UTC, merged